/**
 * INTELLIC Scheduler Module - INTELLIC-Compatible Wrapper
 *
 * This wraps our existing scheduler service to be compatible with INTELLIC's Module pattern.
 * It demonstrates how to bridge existing services to the Spezi architecture.
 *
 * Reference: https://github.com/StanfordSpezi/SpeziScheduler
 */

import { BaseModule, type ModuleMetadata } from '../Module';
import { Injectable } from '../Dependency';
import schedulerService from '@/services/scheduler';
import type { ScheduledTask, RecurrenceRule } from '@/types';
import { logger } from '@/utils/logger';

/**
 * Scheduler Module - Spezi-compatible wrapper around our scheduler service
 *
 * Provides Spezi-style API while using our existing implementation underneath.
 */
@Injectable('scheduler')
export class SchedulerModule extends BaseModule {
  metadata: ModuleMetadata = {
    id: 'scheduler',
    name: 'SpeziScheduler',
    version: '1.0.0',
    description: 'Task scheduling with recurrence rules',
    dependencies: ['storage', 'notifications'],
  };

  /**
   * Configure the scheduler module
   */
  async configure(): Promise<void> {
    // Perform any initialization needed
    console.log('[SchedulerModule] Configured');
  }

  /**
   * Create or update a task (Spezi-style API)
   *
   * Matches Spezi's createOrUpdateTask signature as closely as possible
   * while adapting to our web-based implementation.
   */
  async createOrUpdateTask(params: {
    id: string;
    title: string;
    userId: string;
    instructions?: string;
    category?: TaskCategory;
    schedule?: Schedule;
    completionPolicy?: CompletionPolicy;
    scheduleNotifications?: boolean;
    tags?: string[];
    effectiveFrom?: Date;
  }): Promise<void> {
    const {
      id: _id, // Kept for API compatibility, but ID is auto-generated
      title,
      userId,
      instructions,
      category,
      schedule,
      completionPolicy = 'anytime',
      scheduleNotifications = true,
      tags = [],
      effectiveFrom = new Date(),
    } = params;

    // Convert Spezi-style schedule to our RecurrenceRule
    const recurrence = schedule ? this.convertScheduleToRecurrence(schedule) : undefined;

    // Create task using our existing service
    const task: Omit<ScheduledTask, 'id'> = {
      userId,
      title,
      description: instructions,
      taskType: category?.type || 'reminder',
      status: 'pending',
      scheduledFor: effectiveFrom,
      recurrence,
      metadata: {
        category: category?.name,
        tags,
        completionPolicy,
        scheduleNotifications,
      },
    };

    // Note: id will be auto-generated by scheduleTask
    await schedulerService.scheduleTask(userId, task);
  }

  /**
   * Query tasks
   *
   * Spezi-style query interface
   */
  async queryTasks(params: {
    userId: string;
    predicate?: TaskPredicate;
    sortBy?: TaskSortOrder;
    fetchLimit?: number;
  }): Promise<ScheduledTask[]> {
    const { userId, predicate, fetchLimit } = params;

    // Get tasks from our service
    let tasks = await schedulerService.getUserTasks(userId);

    // Apply predicate filtering if provided
    if (predicate) {
      tasks = tasks.filter((task) => this.applyPredicate(task, predicate));
    }

    // Apply limit
    if (fetchLimit) {
      tasks = tasks.slice(0, fetchLimit);
    }

    return tasks;
  }

  /**
   * Delete task versions
   *
   * Note: This implementation requires userId to be stored with tasks.
   * Alternative: Use deleteTasksForUser() with explicit userId parameter.
   */
  async deleteTasks(taskIds: string[]): Promise<void> {
    // Web implementation limitation: We need userId to delete tasks from Firestore
    // Tasks are stored at: users/{userId}/tasks/{taskId}
    //
    // Spezi iOS stores tasks with SwiftData which doesn't require userId in path.
    // For web, we need to either:
    // 1. Query each task to find its userId (expensive)
    // 2. Use deleteTasksForUser() instead (recommended)
    //
    // For now, we'll log a warning. Use deleteTasksForUser() for actual deletion.

    logger.warn(
      '[SchedulerModule] deleteTasks() cannot delete without userId context. ' +
      'Use deleteTasksForUser(userId, taskIds) instead.',
      { taskIds }
    );

    throw new Error(
      'deleteTasks() requires userId context in web implementation. ' +
      'Use deleteTasksForUser(userId, taskIds) instead.'
    );
  }

  /**
   * Delete tasks for a specific user (Web-specific method)
   *
   * This is the recommended method for deleting tasks in the web implementation.
   */
  async deleteTasksForUser(userId: string, taskIds: string[]): Promise<void> {
    try {
      for (const taskId of taskIds) {
        await schedulerService.deleteTask(userId, taskId);
      }

      logger.info('Tasks deleted', { userId, count: taskIds.length });
    } catch (error) {
      logger.error('Failed to delete tasks', error);
      throw error;
    }
  }

  /**
   * Convert Spezi-style schedule to our RecurrenceRule
   */
  private convertScheduleToRecurrence(schedule: Schedule): RecurrenceRule | undefined {
    switch (schedule.type) {
      case 'daily':
        return {
          frequency: 'daily',
          interval: 1,
          endDate: schedule.endingAt,
        };
      case 'weekly':
        return {
          frequency: 'weekly',
          interval: 1,
          daysOfWeek: schedule.daysOfWeek,
          endDate: schedule.endingAt,
        };
      case 'monthly':
        return {
          frequency: 'monthly',
          interval: 1,
          endDate: schedule.endingAt,
        };
      case 'once':
        // One-time schedules don't use recurrence
        return undefined;
      default:
        return undefined;
    }
  }

  /**
   * Apply predicate filtering
   */
  private applyPredicate(task: ScheduledTask, predicate: TaskPredicate): boolean {
    if (predicate.status && task.status !== predicate.status) {
      return false;
    }
    if (predicate.startDate && new Date(task.scheduledFor) < predicate.startDate) {
      return false;
    }
    if (predicate.endDate && new Date(task.scheduledFor) > predicate.endDate) {
      return false;
    }
    if (predicate.tags && predicate.tags.length > 0) {
      const taskTags = (task.metadata?.tags as string[]) || [];
      if (!predicate.tags.some((tag) => taskTags.includes(tag))) {
        return false;
      }
    }
    return true;
  }
}

/**
 * Spezi-style type definitions
 */

export interface TaskCategory {
  name: string;
  type: 'questionnaire' | 'assessment' | 'reminder' | 'data_collection';
  icon?: string;
}

export type Schedule =
  | {
      type: 'daily';
      hour: number;
      minute: number;
      startingAt?: Date;
      endingAt?: Date;
    }
  | {
      type: 'weekly';
      daysOfWeek: number[];
      hour: number;
      minute: number;
      startingAt?: Date;
      endingAt?: Date;
    }
  | {
      type: 'monthly';
      dayOfMonth: number;
      hour: number;
      minute: number;
      startingAt?: Date;
      endingAt?: Date;
    }
  | {
      type: 'once';
      startingAt?: Date;
    };

export type CompletionPolicy = 'anytime' | 'on_time' | 'strict';

export interface TaskPredicate {
  status?: 'pending' | 'in_progress' | 'completed' | 'missed' | 'cancelled';
  startDate?: Date;
  endDate?: Date;
  tags?: string[];
}

export type TaskSortOrder = 'scheduledFor' | 'createdAt' | 'title';

/**
 * Export singleton instance for convenience
 */
export const schedulerModule = new SchedulerModule();
